name: CI

on:
  pull_request:
  push:
    branches: [main, master, "release/*"]

jobs:
  ci:
    uses: nikolareljin/ci-helpers/.github/workflows/python-scan.yml@bbdb7f773d84db65af1bba6ed56717457b3f4088
    with:
      python_version: "3.11"
      working_directory: "."
      
