name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    uses: nikolareljin/ci-helpers/.github/workflows/presets/python.yml@0.1.1
    with:
      python_version: "3.11"
      lint_command: >-
        git submodule update --init --recursive &&
        python -m pip install --upgrade pip &&
        python -m pip install -e .[dev] &&
        scripts/lint.sh
      test_command: "scripts/run_tests.sh"
