name: CI

on:
  pull_request:
  push:
    branches: [main, master, "release/*"]

jobs:
  ci:
    uses: nikolareljin/ci-helpers/.github/workflows/python-scan.yml@4a1f1d7ad5f84ec101b87fdad2b534f38859c5c5

    with:
      python_version: "3.11"
      working_directory: "."
